appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: VzTuVV+fJoCzQhuZS3pWj2rL5qOQ8tY3TtkilOZRbVBbHthLR0E6Jl+YDvRBWLy3T8Ils94+tjWTVTiuOevlUNLgkRptFq52eRvdIxPyj5aUQG9Rc5fRJzohe/Wswwd/E+3LAqLsSr5jv82DOYf12+Lwuaa1r2dHtGLDeQkB8aPOWd+y5VfZS3ssYgCdQB/63dTUSvLedns9t1Trfp1u9AbLduiuRzx+HNzAGqktU1arsJ3D5C9PI+PkRiO1P0CUIHILEBqsM3R6gFdYlTDVi5VjFXqj4qlaNWIfkJVhBGFQNPjye87RGi8N6oZZgtMoL2lPJ4/lDKU4xenyJy+knPK/la4mX+NqZD9+tQvwfrFtNHQQelYTnf0YG87siNY6wIsUY1MatDzINA50Csq+R92dW5Hq3Fpl+zhLnNNo6SgvmxgZsjWJzPdqkMdP8vCWbdlPho9hYmtZ+hLz37WEq78ZhW1YRP8Y/1bm/MSliFe0kyp1k4O3sw9vxK/2phRGc7yR1CnEVpDMqk5PQmlHdpKLurOyjHTf+ANk0aADaWNBvPuFG1iITCC5fffoG0TdDUbbtmlYIgmcSCEygskkfItDkso9Ptgd0i1iPBj7JhiPsaqrAM7hSjEg8JJzE7OWQiaVVYU+WwA9kohDLtuq9C2cNo1aSPpMWbpqc89NkPc=}
provider:
  win: azure
conda_forge_output_validation: true
